"""Add last_accessed and progress constraint to UserModul

Revision ID: 60e23eda99dc
Revises: 3dae252d2df3
Create Date: 2025-06-24 18:41:48.975791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e23eda99dc'
down_revision = '3dae252d2df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_moduls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_accessed', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_moduls', schema=None) as batch_op:
        batch_op.drop_column('last_accessed')

    # ### end Alembic commands ###
