"""Ubah struktur UserModul ke topik dan submodul

Revision ID: e11f597e3d3f
Revises: 60e23eda99dc
Create Date: 2025-06-24 19:18:28.721561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11f597e3d3f'
down_revision = '60e23eda99dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_moduls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topik', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('submodul', sa.String(length=100), nullable=False))
        batch_op.drop_column('title')
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_moduls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('submodul')
        batch_op.drop_column('topik')

    # ### end Alembic commands ###
